[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cuslines"
version = "2.0.0"
description="GPU-accelerated tractography package"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "nibabel",
    "tqdm",
    "dipy",
    "trx-python",
    "cuda-python",
    "cuda-core",
    "cuda-cccl"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["cuslines*"]
